 [profile.default]
src = "src"
out = "out"
libs = ["lib"]

eth_rpc_url = 'https://rpc.ankr.com/eth_sepolia'
etherscan_api_key = '${ETHERSCAN_KEY}'

<<<<<<< HEAD
[rpc_endpoints]
sepolia = "https://rpc.sepolia.org"

[etherscan]
sepolia = { key = "XXXXXXXXXXXXXXXXXXXX" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
=======
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
>>>>>>> 26b57b4 (fallback sol maintenance)
